apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      nodePort: 30080
  type: NodePort
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: nginx-loadbalancer
#  namespace: nginx
#spec:
#  selector:
#    app: nginx
#  ports:
#    - port: 80
#      targetPort: 80
#  type: LoadBalancer
#apiVersion: v1
#kind: Service
#metadata:
#  name: nginx
#  labels:
#    app: nginx
#  namespace: nginx
#spec:
#  type: ClusterIP
#  selector:
#    app: nginx
#  ports:
#    - port: 80
#      targetPort: 80
#      protocol: TCP
#      name: nginx