apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  namespace: nginx
spec:
  rules:
  - host: "k8s-cluster-endpoint"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx-loadbalancer
            port:
              number: 80