apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx.conf
  labels:
    app: nginx
  namespace: nginx
data:
  nginx.conf: |-
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       80;
          location / {
              return 200 'gangnam style!';
          }
      }
    }